### ISSUE TITLE
Simplify ordering of menu item categories

### ISSUE THREAD

**Issue by andygoossens** [math2k/frietjes#25]
When creating a new "Menu item category" you have to enter a "order" value. If someone makes a mistake and uses the same value as another category (from the same food provider), then items of both categories will be mixed on the new user order screen.

Ideally the software should pick the "order" value for you. Maybe the next available value for that food provider?

Additionally, it would be nice that reordering categories would be made easier. At the moment, if you want that a certain category appears earlier, then you would need to change the "order" numbers of all categories that lie in between. A potential solution might be to have a dedicated page where you can select a category from the list and just press an "up" or "down" button.

**Comment by math2k** [comment]
Added adminsortable2
